#This is sample of properties file
#I am writing the key , your wish you can take any

my.db.driver=OracleDriver
my.db.url=jdbc:oracle:thin:sample
my.db.user=root
my.adb.pwd=root
#you can use ., - , _ anything



